export const copy = {
  nav: {
    dashboard: 'Dashboard',
    channels: 'Canali',
    runs: 'Run',
    settings: 'Impostazioni',
    logout: 'Esci',
  },
  dashboard: {
    title: 'Dashboard',
    runStatusTitle: 'Stato pipeline',
    runNow: 'Avvia pipeline ora',
    runInProgress: 'Pipeline in corso…',
    runInProgressStatus: (runId: number | undefined, processed: number) =>
      `Pipeline in corso (run #${runId ?? '?'}, ${processed} canali processati)`,
    runCompleted: 'completato',
    runFailed: 'fallito',
    runCancelled: 'cancellato',
    runCooldown: 'Pipeline non avviata oggi',
    queuesTitle: 'Code',
    quotaToday: 'Quota YouTube oggi',
    unitsUsed: (n: number, cap: number) =>
      `${n.toLocaleString('it-IT')} / ${cap.toLocaleString('it-IT')} unità`,
    queueCandidates: 'Nuovi candidati',
    queueEnriched: 'In attesa di qualifica',
    queueQualifiedNoEmail: 'Qualificati senza email',
    queueDrafted: 'Bozze in attesa di invio',
    queueSentNoReply: 'Inviati senza risposta',
    topRecent: 'Ultimi canali qualificati',
    noData: 'Nessun dato ancora — avvia la pipeline per cominciare.',
    llmToday: 'LLM oggi',
    llmCalls: 'Chiamate',
    llmTokensInput: 'Token input',
    llmTokensOutput: 'Token output',
    quotaNoUsage: 'Nessun utilizzo oggi',
  },
  channels: {
    title: 'Canali',
    columnThumbnail: '',
    columnTitle: 'Titolo',
    columnSubscribers: 'Iscritti',
    columnNiche: 'Nicchia',
    columnFormat: 'Format',
    columnScore: 'Score',
    columnPitchLanguage: 'Lingua pitch',
    columnOutreachStatus: 'Outreach',
    columnLastQualified: 'Ultima qualifica',
    filtersTitle: 'Filtri',
    filterOutreachStatus: 'Stato outreach',
    filterMinScore: 'Score minimo',
    filterMaxScore: 'Score massimo',
    filterMinSubs: 'Iscritti minimi',
    filterMaxSubs: 'Iscritti massimi',
    filterNiche: 'Nicchia contiene',
    filterFormat: 'Format contiene',
    filterPitchLanguage: 'Lingua pitch',
    search: 'Cerca per titolo, handle o descrizione',
    sortScoreDesc: 'Score ↓',
    sortSubsDesc: 'Iscritti ↓',
    sortQualifiedDesc: 'Qualifica più recente',
    sortDiscoveredDesc: 'Scoperta più recente',
    paginationNext: 'Successivi',
    paginationPrev: 'Precedenti',
    pageOf: (page: number, total: number) => `Pagina ${page} di ${total}`,
    noResults: 'Nessun canale corrisponde ai filtri.',
    resetFilters: 'Reset filtri',
    clearFilters: 'Cancella filtri',
    pitchLangAll: 'Tutte',
    pitchLangIt: 'Italiano',
    pitchLangEn: 'Inglese',
  },
  outreachStatus: {
    none: 'Da rivedere',
    email_added: 'Email aggiunta',
    drafted: 'Bozza pronta',
    sent: 'Inviata',
    replied: 'Risposta ricevuta',
    no_reply: 'Nessuna risposta',
    ignored: 'Ignorato',
  },
};
