export const copy = {
  nav: {
    dashboard: 'Dashboard',
    channels: 'Canali',
    runs: 'Run',
    settings: 'Impostazioni',
    logout: 'Esci',
    toggleTheme: 'Cambia tema',
  },
  dashboard: {
    title: 'Dashboard',
    runStatusTitle: 'Stato pipeline',
    runNow: 'Avvia pipeline ora',
    runInProgress: 'Pipeline in corso…',
    runInProgressStatus: (runId: number | undefined, processed: number) =>
      `Pipeline in corso (run #${runId ?? '?'}, ${processed} canali processati)`,
    runCompleted: 'completato',
    runFailed: 'fallito',
    runCancelled: 'cancellato',
    runCooldown: 'Pipeline non avviata oggi',
    queuesTitle: 'Code',
    quotaToday: 'Quota YouTube oggi',
    unitsUsed: (n: number, cap: number) =>
      `${n.toLocaleString('it-IT')} / ${cap.toLocaleString('it-IT')} unità`,
    queueCandidates: 'Nuovi candidati',
    queueEnriched: 'In attesa di qualifica',
    queueQualifiedNoEmail: 'Qualificati senza email',
    queueDrafted: 'Bozze in attesa di invio',
    queueSentNoReply: 'Inviati senza risposta',
    topRecent: 'Ultimi canali qualificati',
    noData: 'Nessun dato ancora — avvia la pipeline per cominciare.',
    llmToday: 'LLM oggi',
    llmCalls: 'Chiamate',
    llmTokensInput: 'Token input',
    llmTokensOutput: 'Token output',
    llmCostToday: 'Costo stimato',
    quotaNoUsage: 'Nessun utilizzo oggi',
    toastPipelineStarted: 'Pipeline avviata',
    toastPipelineAlreadyRunning: (runId: number | string) =>
      `Pipeline già in corso (run #${runId})`,
    toastPipelineStartError: "Errore durante l'avvio",
    toastNetworkError: 'Errore di rete',
    runLastStatus: (id: number, label: string, time: string) =>
      `Ultimo run #${id} ${label} — ${time}`,
  },
  channels: {
    title: 'Canali',
    columnThumbnail: '',
    columnTitle: 'Titolo',
    columnSubscribers: 'Iscritti',
    columnNiche: 'Nicchia',
    columnFormat: 'Format',
    columnScore: 'Score',
    columnPitchLanguage: 'Lingua pitch',
    columnOutreachStatus: 'Outreach',
    columnLastQualified: 'Ultima qualifica',
    filtersTitle: 'Filtri',
    filterOutreachStatus: 'Stato outreach',
    filterMinScore: 'Score minimo',
    filterMaxScore: 'Score massimo',
    filterMinSubs: 'Iscritti minimi',
    filterMaxSubs: 'Iscritti massimi',
    filterNiche: 'Nicchia contiene',
    filterFormat: 'Format contiene',
    filterPitchLanguage: 'Lingua pitch',
    search: 'Cerca per titolo, handle o descrizione',
    sortScoreDesc: 'Score ↓',
    sortSubsDesc: 'Iscritti ↓',
    sortQualifiedDesc: 'Qualifica più recente',
    sortDiscoveredDesc: 'Scoperta più recente',
    paginationNext: 'Successivi',
    paginationPrev: 'Precedenti',
    pageOf: (page: number, total: number) => `Pagina ${page} di ${total}`,
    noResults: 'Nessun canale corrisponde ai filtri.',
    resetFilters: 'Reset filtri',
    clearFilters: 'Cancella filtri',
    pitchLangAll: 'Tutte',
    pitchLangIt: 'Italiano',
    pitchLangEn: 'Inglese',
    exportCsv: 'Esporta CSV con questi filtri',
  },
  outreachStatus: {
    none: 'Da rivedere',
    email_added: 'Email aggiunta',
    drafted: 'Bozza pronta',
    sent: 'Inviata',
    replied: 'Risposta ricevuta',
    no_reply: 'Nessuna risposta',
    ignored: 'Ignorato',
  },
  channelDetail: {
    notFound: 'Canale non trovato.',
    discoveryViaKeyword: (kw: string) => `Trovato via keyword: ${kw}`,
    discoveryViaCategory: (name: string) => `Trovato in categoria: ${name}`,
    openOnYoutube: 'Apri su YouTube',
    subscribers: 'iscritti',
    totalVideos: 'video totali',
    country: 'Paese',
    language: 'Lingua',
    channelCreated: 'Canale creato il',
    description: 'Descrizione',
    recentVideos: 'Video recenti',
    noVideos: 'Nessun video scaricato.',

    // AI assessment
    assessmentTitle: 'Valutazione AI',
    score: 'Score',
    niche: 'Nicchia',
    format: 'Format',
    pitchLanguage: 'Lingua pitch',
    confidence: 'Confidence',
    rationale: 'Razionale',
    suggestedSolution: 'Soluzione suggerita',
    pitchAngle: 'Angolo di pitch',
    automatableWorkflows: 'Workflow automatizzabili',
    timeSavedPerVideo: (m: number) => `~${m} min risparmiati per video`,
    signals: 'Segnali',
    positiveSignals: 'Positivi',
    negativeSignals: 'Negativi',
    disqualifiers: 'Squalificanti',
    noDisqualifiers: 'Nessuno',
    modelUsed: 'Modello',
    qualifiedAt: 'Qualificato il',
    rawJsonLink: 'JSON grezzo',
    requalifyButton: 'Riqualifica',
    requalifying: 'Qualifica in corso…',
    notQualified: 'Non ancora qualificato.',

    // Agent reasoning panel
    whyTheseVideosTitle: 'Perché questi video',
    formatConsistency: 'Consistenza dei format',
    selectionRationale: 'Razionale di selezione',
    classificationTable: 'Classificazione dei 20 video',
    columnClassification: 'Classificazione',
    columnRelevance: 'Rilevanza',
    columnReasoning: 'Motivazione',
    classificationLabel: {
      format_anchor: 'Anchor di format',
      representative: 'Rappresentativo',
      extemporaneous: 'Estemporaneo',
      outlier: 'Outlier',
    },
    viewTranscript: 'Vedi transcript',
    transcriptUnavailable: 'Transcript non disponibile',
    transcriptModalTitle: (videoTitle: string) => `Transcript — ${videoTitle}`,

    // Outreach widget
    outreachTitle: 'Outreach',
    emailLabel: 'Email di contatto',
    emailPlaceholder: 'esempio@dominio.it',
    emailSaveButton: 'Salva email e genera bozza',
    generatingDraft: 'Sto generando la bozza…',
    draftSubject: 'Oggetto',
    draftBody: 'Corpo',
    copyToClipboard: 'Copia (Oggetto + Corpo)',
    copied: 'Copiato!',
    regenerate: 'Rigenera bozza',
    regenerating: 'Rigenero…',
    markAsSent: 'Segna come inviata',
    sentAt: (d: string) => `Inviata il ${d}`,
    markAsReplied: 'Risposta ricevuta',
    markAsNoReply: 'Nessuna risposta',
    markAsIgnored: 'Ignorato',
    reopen: 'Riapri',
    notesLabel: 'Note',
    notesPlaceholder: 'Note interne libere…',
    draftHistory: 'Cronologia bozze',
    draftHistoryEmpty: 'Nessuna bozza precedente.',
    viewDraft: 'Visualizza',
    draftGenerationError: 'Errore durante la generazione della bozza',
    draftGenerationFailed: 'Generazione bozza non riuscita.',
    retryButton: 'Riprova',
    subjectPrefix: (subject: string) => `Oggetto: ${subject}`,

    // Description expand/collapse
    showMore: 'Mostra altro',
    showLess: 'Mostra meno',
    deleteConfirmTypePrefix: 'Digita',
    deleteConfirmTypeSuffix: 'per confermare',

    // Transcript footer
    transcriptCharCount: (n: number) => `${n.toLocaleString('it-IT')} caratteri`,
    transcriptSource: 'via youtube-transcript',

    // Error page
    errorTitle: 'Si è verificato un errore',
    errorBody: 'Impossibile caricare i dettagli del canale. Riprova o torna alla lista dei canali.',
    errorRetry: 'Riprova',
    errorBackToChannels: 'Torna ai canali',

    // GDPR
    deleteChannel: 'Elimina canale',
    deleteChannelConfirmTitle: 'Eliminare definitivamente questo canale?',
    deleteChannelConfirmBody:
      "Saranno rimossi i dati del canale, le valutazioni AI, i transcript e le bozze. L'azione è irreversibile.",
    deleteChannelConfirmAction: 'Elimina',
    deleteChannelCancel: 'Annulla',
  },
  runs: {
    title: 'Run della pipeline',
    emptyState: 'Nessun run ancora — avvia la pipeline dal cruscotto.',
    columnId: '#',
    columnStartedAt: 'Avviato',
    columnFinishedAt: 'Concluso',
    columnTriggeredBy: 'Avviato da',
    columnStatus: 'Stato',
    columnCandidates: 'Candidati',
    columnQualified: 'Qualificati',
    columnQuota: 'Quota',
    columnLlmTokens: 'Token LLM',
    triggeredByLabel: { cron: 'Programmato', manual: 'Manuale' },
    statusLabel: {
      running: 'In corso',
      completed: 'Completato',
      failed: 'Fallito',
      cancelled: 'Annullato',
    },
    durationLabel: (s: number) => `${Math.floor(s / 60)} min ${s % 60} s`,
    runDetailTitle: (id: number) => `Run #${id}`,
    backToRuns: '← Tutti i run',
    countersTitle: 'Contatori',
    counterSearches: 'Ricerche keyword',
    counterCandidates: 'Candidati trovati',
    counterEnriched: 'Canali arricchiti',
    counterPreRejected: 'Pre-scartati',
    counterQualified: 'Qualificati',
    counterPostRejected: 'Scartati dopo qualifica',
    counterQuota: 'Unità quota usate',
    counterLlmCalls: 'Chiamate LLM',
    counterLlmTokensInput: 'Token input',
    counterLlmTokensOutput: 'Token output',
    counterLlmCost: 'Costo LLM',
    errorTitle: 'Errore',
    eventsTitle: 'Eventi',
    noEvents: 'Nessun evento registrato.',
    eventColumnTime: 'Quando',
    eventColumnStage: 'Stadio',
    eventColumnEvent: 'Evento',
    eventColumnChannel: 'Canale',
    eventColumnDetails: 'Dettagli',
    loadPrevious: 'Carica i precedenti',
    autoRefresh: 'Aggiornamento automatico',
    filterAll: 'Tutti gli stadi',
    filterApply: 'Filtra',
    filterReset: 'Azzera filtri',
    channelIdPlaceholder: 'ID canale',
    errorStackTrace: 'Traccia dello stack',
  },
  settings: {
    title: 'Impostazioni',

    // Filtri
    filtersTitle: 'Filtri di pre-qualifica',
    filtersDescription: 'Applicati prima della valutazione AI per scartare canali fuori scope.',
    minSubscribers: 'Iscritti minimi',
    maxSubscribers: 'Iscritti massimi',
    country: 'Paese (ISO 2 lettere)',
    language: 'Lingua (ISO 2 lettere)',
    requalifyAfterDays: 'Riqualifica dopo (giorni)',
    inactiveDays: 'Soglia inattività (giorni senza upload)',
    saveFilters: 'Salva filtri',
    filtersSaved: 'Filtri aggiornati.',

    // Keywords
    keywordsTitle: 'Keyword di ricerca',
    keywordsDescription:
      'Le keyword vengono ruotate ogni run: le meno usate vengono scelte per prime.',
    columnKeyword: 'Keyword',
    columnIsActive: 'Attiva',
    columnLastUsedAt: 'Ultimo uso',
    columnTotalUses: 'Usi totali',
    columnTotalCandidates: 'Candidati prodotti',
    columnNotes: 'Note',
    addKeywordTitle: 'Aggiungi keyword',
    addKeywordButton: 'Aggiungi',
    newKeywordPlaceholder: 'es. "rassegna stampa quotidiana"',
    newKeywordNotesPlaceholder: 'Note opzionali…',
    deactivate: 'Disattiva',
    activate: 'Attiva',
    keywordActive: 'Attiva',
    keywordInactive: 'Inattiva',
    deleteKeyword: 'Elimina',
    deleteKeywordConfirm: 'Eliminare definitivamente questa keyword?',
    keywordAdded: 'Keyword aggiunta.',
    keywordUpdated: 'Keyword aggiornata.',
    keywordDeleted: 'Keyword eliminata.',

    // Pipeline config
    pipelineConfigTitle: 'Configurazione pipeline',
    keywordsPerRun: 'Keyword per run',
    targetQualifiedPerRun: 'Target qualificati per run',
    savePipelineConfig: 'Salva configurazione',
    pipelineConfigSaved: 'Configurazione aggiornata.',

    // Read-only env
    modelsTitle: 'Modelli LLM (sola lettura, da .env)',
    modelThink: 'Modello "think"',
    modelFast: 'Modello "fast"',
    llmBaseUrl: 'Endpoint proxy LLM',
    promptsTitle: 'Versioni prompt (sola lettura)',
    promptSelect: 'Selezione video',
    promptQualify: 'Qualifica finale',
    promptDraft: 'Bozza outreach',

    // Export
    exportTitle: 'Esporta dati',
    exportDescription: 'Esporta tutti i canali (con i filtri applicabili) in CSV.',
    exportButton: 'Scarica CSV dei canali',
    exportRunning: 'Generazione in corso…',
    saving: 'Salvataggio in corso…',
    cancel: 'Annulla',
    keywordDuplicate: (kw: string) => `"${kw}" è già presente.`,
    keywordAddError: "Errore durante l'aggiunta.",

    // Read-only section footnotes
    modelsFootnote: 'Modificare nel file `.env` e riavviare il worker.',
    promptsFootnote: 'I prompt sono versionati nel codice (`src/lib/llm/prompts/`).',
  },
};
